name: Run

on:
  push:
    branches: [ main ]

jobs:
  run_bot:
    runs-on: ubuntu-latest
    steps:
      - name: Run the telegram bot
        run: |
          curl -fsSLo telegram-bot https://github.com/mbtamuli/didactic-train/releases/latest/download/telegram-bot_linux_amd64
          chmod +x telegram-bot
          ./telegram-bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}